# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: market_depth.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'market_depth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12market_depth.proto\x12\x0fmt5.marketdepth\x1a\x0btypes.proto\"\x1f\n\rSymbolRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"L\n\x13MarketDepthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12$\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x13.mt5.types.BookInfo2\xaa\x02\n\x12MarketDepthService\x12\\\n\x14SubscribeMarketDepth\x12\x1e.mt5.marketdepth.SymbolRequest\x1a$.mt5.marketdepth.MarketDepthResponse\x12V\n\x0eGetMarketDepth\x12\x1e.mt5.marketdepth.SymbolRequest\x1a$.mt5.marketdepth.MarketDepthResponse\x12^\n\x16UnsubscribeMarketDepth\x12\x1e.mt5.marketdepth.SymbolRequest\x1a$.mt5.marketdepth.MarketDepthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_depth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYMBOLREQUEST']._serialized_start=52
  _globals['_SYMBOLREQUEST']._serialized_end=83
  _globals['_MARKETDEPTHRESPONSE']._serialized_start=85
  _globals['_MARKETDEPTHRESPONSE']._serialized_end=161
  _globals['_MARKETDEPTHSERVICE']._serialized_start=164
  _globals['_MARKETDEPTHSERVICE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
