# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: market_data.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'market_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11market_data.proto\x12\x0emt5.marketdata\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0btypes.proto\"\x1f\n\rSymbolRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"\x1f\n\x0eSymbolsRequest\x12\r\n\x05group\x18\x01 \x01(\t\"%\n\x14SymbolsTotalResponse\x12\r\n\x05total\x18\x01 \x01(\x05\"9\n\x0fSymbolsResponse\x12&\n\x07symbols\x18\x01 \x03(\x0b\x32\x15.mt5.types.SymbolInfo\"5\n\x13SelectSymbolRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\"\'\n\x14SelectSymbolResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9a\x03\n\x11MarketDataService\x12O\n\x0fGetSymbolsTotal\x12\x16.google.protobuf.Empty\x1a$.mt5.marketdata.SymbolsTotalResponse\x12M\n\nGetSymbols\x12\x1e.mt5.marketdata.SymbolsRequest\x1a\x1f.mt5.marketdata.SymbolsResponse\x12\x45\n\rGetSymbolInfo\x12\x1d.mt5.marketdata.SymbolRequest\x1a\x15.mt5.types.SymbolInfo\x12\x43\n\x11GetSymbolInfoTick\x12\x1d.mt5.marketdata.SymbolRequest\x1a\x0f.mt5.types.Tick\x12Y\n\x0cSelectSymbol\x12#.mt5.marketdata.SelectSymbolRequest\x1a$.mt5.marketdata.SelectSymbolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYMBOLREQUEST']._serialized_start=79
  _globals['_SYMBOLREQUEST']._serialized_end=110
  _globals['_SYMBOLSREQUEST']._serialized_start=112
  _globals['_SYMBOLSREQUEST']._serialized_end=143
  _globals['_SYMBOLSTOTALRESPONSE']._serialized_start=145
  _globals['_SYMBOLSTOTALRESPONSE']._serialized_end=182
  _globals['_SYMBOLSRESPONSE']._serialized_start=184
  _globals['_SYMBOLSRESPONSE']._serialized_end=241
  _globals['_SELECTSYMBOLREQUEST']._serialized_start=243
  _globals['_SELECTSYMBOLREQUEST']._serialized_end=296
  _globals['_SELECTSYMBOLRESPONSE']._serialized_start=298
  _globals['_SELECTSYMBOLRESPONSE']._serialized_end=337
  _globals['_MARKETDATASERVICE']._serialized_start=340
  _globals['_MARKETDATASERVICE']._serialized_end=750
# @@protoc_insertion_point(module_scope)
