# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import market_depth_pb2 as market__depth__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in market_depth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketDepthServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeMarketDepth = channel.unary_unary(
                '/mt5.marketdepth.MarketDepthService/SubscribeMarketDepth',
                request_serializer=market__depth__pb2.SymbolRequest.SerializeToString,
                response_deserializer=market__depth__pb2.MarketDepthResponse.FromString,
                _registered_method=True)
        self.GetMarketDepth = channel.unary_unary(
                '/mt5.marketdepth.MarketDepthService/GetMarketDepth',
                request_serializer=market__depth__pb2.SymbolRequest.SerializeToString,
                response_deserializer=market__depth__pb2.MarketDepthResponse.FromString,
                _registered_method=True)
        self.UnsubscribeMarketDepth = channel.unary_unary(
                '/mt5.marketdepth.MarketDepthService/UnsubscribeMarketDepth',
                request_serializer=market__depth__pb2.SymbolRequest.SerializeToString,
                response_deserializer=market__depth__pb2.MarketDepthResponse.FromString,
                _registered_method=True)


class MarketDepthServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SubscribeMarketDepth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarketDepth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsubscribeMarketDepth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDepthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeMarketDepth': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribeMarketDepth,
                    request_deserializer=market__depth__pb2.SymbolRequest.FromString,
                    response_serializer=market__depth__pb2.MarketDepthResponse.SerializeToString,
            ),
            'GetMarketDepth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketDepth,
                    request_deserializer=market__depth__pb2.SymbolRequest.FromString,
                    response_serializer=market__depth__pb2.MarketDepthResponse.SerializeToString,
            ),
            'UnsubscribeMarketDepth': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsubscribeMarketDepth,
                    request_deserializer=market__depth__pb2.SymbolRequest.FromString,
                    response_serializer=market__depth__pb2.MarketDepthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt5.marketdepth.MarketDepthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mt5.marketdepth.MarketDepthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDepthService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeMarketDepth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.marketdepth.MarketDepthService/SubscribeMarketDepth',
            market__depth__pb2.SymbolRequest.SerializeToString,
            market__depth__pb2.MarketDepthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMarketDepth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.marketdepth.MarketDepthService/GetMarketDepth',
            market__depth__pb2.SymbolRequest.SerializeToString,
            market__depth__pb2.MarketDepthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsubscribeMarketDepth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.marketdepth.MarketDepthService/UnsubscribeMarketDepth',
            market__depth__pb2.SymbolRequest.SerializeToString,
            market__depth__pb2.MarketDepthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
