# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import market_data_pb2 as market__data__pb2
from . import types_pb2 as types__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in market_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketDataServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSymbolsTotal = channel.unary_unary(
                '/mt5.marketdata.MarketDataService/GetSymbolsTotal',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=market__data__pb2.SymbolsTotalResponse.FromString,
                _registered_method=True)
        self.GetSymbols = channel.unary_unary(
                '/mt5.marketdata.MarketDataService/GetSymbols',
                request_serializer=market__data__pb2.SymbolsRequest.SerializeToString,
                response_deserializer=market__data__pb2.SymbolsResponse.FromString,
                _registered_method=True)
        self.GetSymbolInfo = channel.unary_unary(
                '/mt5.marketdata.MarketDataService/GetSymbolInfo',
                request_serializer=market__data__pb2.SymbolRequest.SerializeToString,
                response_deserializer=types__pb2.SymbolInfo.FromString,
                _registered_method=True)
        self.SelectSymbol = channel.unary_unary(
                '/mt5.marketdata.MarketDataService/SelectSymbol',
                request_serializer=market__data__pb2.SelectSymbolRequest.SerializeToString,
                response_deserializer=market__data__pb2.SelectSymbolResponse.FromString,
                _registered_method=True)


class MarketDataServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetSymbolsTotal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSymbols(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSymbolInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectSymbol(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSymbolsTotal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSymbolsTotal,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=market__data__pb2.SymbolsTotalResponse.SerializeToString,
            ),
            'GetSymbols': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSymbols,
                    request_deserializer=market__data__pb2.SymbolsRequest.FromString,
                    response_serializer=market__data__pb2.SymbolsResponse.SerializeToString,
            ),
            'GetSymbolInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSymbolInfo,
                    request_deserializer=market__data__pb2.SymbolRequest.FromString,
                    response_serializer=types__pb2.SymbolInfo.SerializeToString,
            ),
            'SelectSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectSymbol,
                    request_deserializer=market__data__pb2.SelectSymbolRequest.FromString,
                    response_serializer=market__data__pb2.SelectSymbolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt5.marketdata.MarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mt5.marketdata.MarketDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSymbolsTotal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.marketdata.MarketDataService/GetSymbolsTotal',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            market__data__pb2.SymbolsTotalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSymbols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.marketdata.MarketDataService/GetSymbols',
            market__data__pb2.SymbolsRequest.SerializeToString,
            market__data__pb2.SymbolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSymbolInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.marketdata.MarketDataService/GetSymbolInfo',
            market__data__pb2.SymbolRequest.SerializeToString,
            types__pb2.SymbolInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.marketdata.MarketDataService/SelectSymbol',
            market__data__pb2.SelectSymbolRequest.SerializeToString,
            market__data__pb2.SelectSymbolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
