# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rates_pb2 as rates__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rates_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RatesServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CopyRatesFrom = channel.unary_unary(
                '/mt5.rates.RatesService/CopyRatesFrom',
                request_serializer=rates__pb2.RatesFromRequest.SerializeToString,
                response_deserializer=rates__pb2.RatesResponse.FromString,
                _registered_method=True)
        self.CopyRatesFromPos = channel.unary_unary(
                '/mt5.rates.RatesService/CopyRatesFromPos',
                request_serializer=rates__pb2.RatesFromPosRequest.SerializeToString,
                response_deserializer=rates__pb2.RatesResponse.FromString,
                _registered_method=True)
        self.CopyRatesRange = channel.unary_unary(
                '/mt5.rates.RatesService/CopyRatesRange',
                request_serializer=rates__pb2.RatesRangeRequest.SerializeToString,
                response_deserializer=rates__pb2.RatesResponse.FromString,
                _registered_method=True)


class RatesServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CopyRatesFrom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyRatesFromPos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyRatesRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RatesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CopyRatesFrom': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyRatesFrom,
                    request_deserializer=rates__pb2.RatesFromRequest.FromString,
                    response_serializer=rates__pb2.RatesResponse.SerializeToString,
            ),
            'CopyRatesFromPos': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyRatesFromPos,
                    request_deserializer=rates__pb2.RatesFromPosRequest.FromString,
                    response_serializer=rates__pb2.RatesResponse.SerializeToString,
            ),
            'CopyRatesRange': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyRatesRange,
                    request_deserializer=rates__pb2.RatesRangeRequest.FromString,
                    response_serializer=rates__pb2.RatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt5.rates.RatesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mt5.rates.RatesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RatesService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CopyRatesFrom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.rates.RatesService/CopyRatesFrom',
            rates__pb2.RatesFromRequest.SerializeToString,
            rates__pb2.RatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyRatesFromPos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.rates.RatesService/CopyRatesFromPos',
            rates__pb2.RatesFromPosRequest.SerializeToString,
            rates__pb2.RatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyRatesRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.rates.RatesService/CopyRatesRange',
            rates__pb2.RatesRangeRequest.SerializeToString,
            rates__pb2.RatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
