# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rates.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'rates.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import enums_pb2 as enums__pb2
from . import types_pb2 as types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brates.proto\x12\tmt5.rates\x1a\x0b\x65nums.proto\x1a\x0btypes.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x01\n\x10RatesFromRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\'\n\ttimeframe\x18\x02 \x01(\x0e\x32\x14.mt5.enums.Timeframe\x12-\n\tdate_from\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\"p\n\x13RatesFromPosRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\'\n\ttimeframe\x18\x02 \x01(\x0e\x32\x14.mt5.enums.Timeframe\x12\x11\n\tstart_pos\x18\x03 \x01(\x05\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\"\xa8\x01\n\x11RatesRangeRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\'\n\ttimeframe\x18\x02 \x01(\x0e\x32\x14.mt5.enums.Timeframe\x12-\n\tdate_from\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07\x64\x61te_to\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"/\n\rRatesResponse\x12\x1e\n\x05rates\x18\x01 \x03(\x0b\x32\x0f.mt5.types.Rate2\xee\x01\n\x0cRatesService\x12\x46\n\rCopyRatesFrom\x12\x1b.mt5.rates.RatesFromRequest\x1a\x18.mt5.rates.RatesResponse\x12L\n\x10\x43opyRatesFromPos\x12\x1e.mt5.rates.RatesFromPosRequest\x1a\x18.mt5.rates.RatesResponse\x12H\n\x0e\x43opyRatesRange\x12\x1c.mt5.rates.RatesRangeRequest\x1a\x18.mt5.rates.RatesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rates_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RATESFROMREQUEST']._serialized_start=86
  _globals['_RATESFROMREQUEST']._serialized_end=223
  _globals['_RATESFROMPOSREQUEST']._serialized_start=225
  _globals['_RATESFROMPOSREQUEST']._serialized_end=337
  _globals['_RATESRANGEREQUEST']._serialized_start=340
  _globals['_RATESRANGEREQUEST']._serialized_end=508
  _globals['_RATESRESPONSE']._serialized_start=510
  _globals['_RATESRESPONSE']._serialized_end=557
  _globals['_RATESSERVICE']._serialized_start=560
  _globals['_RATESSERVICE']._serialized_end=798
# @@protoc_insertion_point(module_scope)
