# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import trade_pb2 as trade__pb2
from . import types_pb2 as types__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trade_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradeServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrdersTotal = channel.unary_unary(
                '/mt5.trade.TradeService/GetOrdersTotal',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=trade__pb2.OrdersTotalResponse.FromString,
                _registered_method=True)
        self.GetOrders = channel.unary_unary(
                '/mt5.trade.TradeService/GetOrders',
                request_serializer=trade__pb2.OrdersRequest.SerializeToString,
                response_deserializer=trade__pb2.OrdersResponse.FromString,
                _registered_method=True)
        self.GetPositionsTotal = channel.unary_unary(
                '/mt5.trade.TradeService/GetPositionsTotal',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=trade__pb2.PositionsTotalResponse.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/mt5.trade.TradeService/GetPositions',
                request_serializer=trade__pb2.PositionsRequest.SerializeToString,
                response_deserializer=trade__pb2.PositionsResponse.FromString,
                _registered_method=True)
        self.GetHistoryOrdersTotal = channel.unary_unary(
                '/mt5.trade.TradeService/GetHistoryOrdersTotal',
                request_serializer=trade__pb2.HistoryRangeRequest.SerializeToString,
                response_deserializer=trade__pb2.HistoryOrdersTotalResponse.FromString,
                _registered_method=True)
        self.GetHistoryOrders = channel.unary_unary(
                '/mt5.trade.TradeService/GetHistoryOrders',
                request_serializer=trade__pb2.HistoryOrdersRequest.SerializeToString,
                response_deserializer=trade__pb2.HistoryOrdersResponse.FromString,
                _registered_method=True)
        self.GetHistoryDealsTotal = channel.unary_unary(
                '/mt5.trade.TradeService/GetHistoryDealsTotal',
                request_serializer=trade__pb2.HistoryRangeRequest.SerializeToString,
                response_deserializer=trade__pb2.HistoryDealsTotalResponse.FromString,
                _registered_method=True)
        self.GetHistoryDeals = channel.unary_unary(
                '/mt5.trade.TradeService/GetHistoryDeals',
                request_serializer=trade__pb2.HistoryDealsRequest.SerializeToString,
                response_deserializer=trade__pb2.HistoryDealsResponse.FromString,
                _registered_method=True)
        self.CalcMargin = channel.unary_unary(
                '/mt5.trade.TradeService/CalcMargin',
                request_serializer=trade__pb2.CalcMarginRequest.SerializeToString,
                response_deserializer=trade__pb2.CalcMarginResponse.FromString,
                _registered_method=True)
        self.CalcProfit = channel.unary_unary(
                '/mt5.trade.TradeService/CalcProfit',
                request_serializer=trade__pb2.CalcProfitRequest.SerializeToString,
                response_deserializer=trade__pb2.CalcProfitResponse.FromString,
                _registered_method=True)
        self.CheckOrder = channel.unary_unary(
                '/mt5.trade.TradeService/CheckOrder',
                request_serializer=trade__pb2.CheckOrderRequest.SerializeToString,
                response_deserializer=types__pb2.TradeCheckResult.FromString,
                _registered_method=True)
        self.SendOrder = channel.unary_unary(
                '/mt5.trade.TradeService/SendOrder',
                request_serializer=trade__pb2.SendOrderRequest.SerializeToString,
                response_deserializer=types__pb2.TradeSendResult.FromString,
                _registered_method=True)


class TradeServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetOrdersTotal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositionsTotal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoryOrdersTotal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoryOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoryDealsTotal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoryDeals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcMargin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcProfit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrdersTotal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrdersTotal,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=trade__pb2.OrdersTotalResponse.SerializeToString,
            ),
            'GetOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=trade__pb2.OrdersRequest.FromString,
                    response_serializer=trade__pb2.OrdersResponse.SerializeToString,
            ),
            'GetPositionsTotal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositionsTotal,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=trade__pb2.PositionsTotalResponse.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=trade__pb2.PositionsRequest.FromString,
                    response_serializer=trade__pb2.PositionsResponse.SerializeToString,
            ),
            'GetHistoryOrdersTotal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoryOrdersTotal,
                    request_deserializer=trade__pb2.HistoryRangeRequest.FromString,
                    response_serializer=trade__pb2.HistoryOrdersTotalResponse.SerializeToString,
            ),
            'GetHistoryOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoryOrders,
                    request_deserializer=trade__pb2.HistoryOrdersRequest.FromString,
                    response_serializer=trade__pb2.HistoryOrdersResponse.SerializeToString,
            ),
            'GetHistoryDealsTotal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoryDealsTotal,
                    request_deserializer=trade__pb2.HistoryRangeRequest.FromString,
                    response_serializer=trade__pb2.HistoryDealsTotalResponse.SerializeToString,
            ),
            'GetHistoryDeals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoryDeals,
                    request_deserializer=trade__pb2.HistoryDealsRequest.FromString,
                    response_serializer=trade__pb2.HistoryDealsResponse.SerializeToString,
            ),
            'CalcMargin': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcMargin,
                    request_deserializer=trade__pb2.CalcMarginRequest.FromString,
                    response_serializer=trade__pb2.CalcMarginResponse.SerializeToString,
            ),
            'CalcProfit': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcProfit,
                    request_deserializer=trade__pb2.CalcProfitRequest.FromString,
                    response_serializer=trade__pb2.CalcProfitResponse.SerializeToString,
            ),
            'CheckOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOrder,
                    request_deserializer=trade__pb2.CheckOrderRequest.FromString,
                    response_serializer=types__pb2.TradeCheckResult.SerializeToString,
            ),
            'SendOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOrder,
                    request_deserializer=trade__pb2.SendOrderRequest.FromString,
                    response_serializer=types__pb2.TradeSendResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt5.trade.TradeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mt5.trade.TradeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradeService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOrdersTotal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.trade.TradeService/GetOrdersTotal',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            trade__pb2.OrdersTotalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.trade.TradeService/GetOrders',
            trade__pb2.OrdersRequest.SerializeToString,
            trade__pb2.OrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositionsTotal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.trade.TradeService/GetPositionsTotal',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            trade__pb2.PositionsTotalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.trade.TradeService/GetPositions',
            trade__pb2.PositionsRequest.SerializeToString,
            trade__pb2.PositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoryOrdersTotal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.trade.TradeService/GetHistoryOrdersTotal',
            trade__pb2.HistoryRangeRequest.SerializeToString,
            trade__pb2.HistoryOrdersTotalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoryOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.trade.TradeService/GetHistoryOrders',
            trade__pb2.HistoryOrdersRequest.SerializeToString,
            trade__pb2.HistoryOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoryDealsTotal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.trade.TradeService/GetHistoryDealsTotal',
            trade__pb2.HistoryRangeRequest.SerializeToString,
            trade__pb2.HistoryDealsTotalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoryDeals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.trade.TradeService/GetHistoryDeals',
            trade__pb2.HistoryDealsRequest.SerializeToString,
            trade__pb2.HistoryDealsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalcMargin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.trade.TradeService/CalcMargin',
            trade__pb2.CalcMarginRequest.SerializeToString,
            trade__pb2.CalcMarginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalcProfit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.trade.TradeService/CalcProfit',
            trade__pb2.CalcProfitRequest.SerializeToString,
            trade__pb2.CalcProfitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.trade.TradeService/CheckOrder',
            trade__pb2.CheckOrderRequest.SerializeToString,
            types__pb2.TradeCheckResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mt5.trade.TradeService/SendOrder',
            trade__pb2.SendOrderRequest.SerializeToString,
            types__pb2.TradeSendResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
